"""ARCH: schema spine (sport-agnostic reference, events, markets, licence register, audit log).

Creates the shared DB guard functions (append-only, bitemporal, monthly partitions) and
attaches them: audit_log / event_status_history / kickoff_history are append-only;
team_alias / source_entity_map are bitemporal. audit_log is RANGE-partitioned by month.

Revision ID: 0001
Revises:
Create Date: 2026-09-28
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.ddl import (
    DROP_FUNCTIONS_SQL,
    FUNCTIONS_SQL,
    append_only_triggers,
    bitemporal_triggers,
)

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Stable ID for the seeded football sport (PRD 5.2: sport_id is seeded).
FOOTBALL_SPORT_ID = "01K6ARCH00000000000000SPRT"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor_id", sa.CHAR(length=26, collation="C"), nullable=True),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.Text(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("ip_hash", sa.String(length=128), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('user', 'admin', 'system', 'service')",
            name=op.f("ck_audit_log_actor_type"),
        ),
        sa.PrimaryKeyConstraint("at", "id", name=op.f("pk_audit_log")),
        postgresql_partition_by="RANGE (at)",
    )
    op.create_index("ix_audit_log_actor_id", "audit_log", ["actor_id"], unique=False)
    op.create_index("ix_audit_log_target", "audit_log", ["target_type", "target_id"], unique=False)
    op.create_table(
        "bookmaker",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("brand", sa.Text(), nullable=False),
        sa.Column("licence_entity", sa.Text(), nullable=True),
        sa.Column("region", sa.String(length=16), nullable=True),
        sa.Column("site_domain", sa.Text(), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmaker")),
        sa.UniqueConstraint("code", name=op.f("uq_bookmaker_code")),
    )
    op.create_table(
        "source",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("licence_ref", sa.Text(), nullable=False),
        sa.Column("terms_version", sa.Text(), nullable=True),
        sa.Column("terms_date", sa.Date(), nullable=True),
        sa.Column("permitted_display", sa.Boolean(), nullable=False),
        sa.Column("permitted_store", sa.Boolean(), nullable=False),
        sa.Column("retain_after_termination", sa.Boolean(), nullable=False),
        sa.Column("permitted_train", sa.Boolean(), nullable=False),
        sa.Column("permitted_derived", sa.Boolean(), nullable=False),
        sa.Column("attribution_text", sa.Text(), nullable=True),
        sa.Column(
            "jurisdiction_limits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("review_due", sa.Date(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('api', 'historical_import', 'manual')", name=op.f("ck_source_kind")
        ),
        sa.CheckConstraint(
            "NOT enabled OR length(btrim(licence_ref)) > 0",
            name=op.f("ck_source_enabled_requires_licence"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
        sa.UniqueConstraint("code", name=op.f("uq_source_code")),
    )
    op.create_table(
        "sport",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sport")),
        sa.UniqueConstraint("code", name=op.f("uq_sport_code")),
    )
    op.create_table(
        "venue",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("country_code", sa.String(length=8), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venue")),
    )
    op.create_table(
        "bookmaker_ruleset",
        sa.Column("bookmaker_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("void_policy_class", sa.String(length=128), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("reviewed_by", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_bookmaker_ruleset_version_positive")),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmaker.id"],
            name=op.f("fk_bookmaker_ruleset_bookmaker_id_bookmaker"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmaker_ruleset")),
        sa.UniqueConstraint(
            "bookmaker_id", "version", name=op.f("uq_bookmaker_ruleset_bookmaker_id_version")
        ),
    )
    op.create_table(
        "competition",
        sa.Column("sport_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("country_code", sa.String(length=8), nullable=True),
        sa.Column("tier", sa.Integer(), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('league', 'cup', 'other')", name=op.f("ck_competition_kind")),
        sa.ForeignKeyConstraint(
            ["sport_id"], ["sport.id"], name=op.f("fk_competition_sport_id_sport")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition")),
        sa.UniqueConstraint("code", name=op.f("uq_competition_code")),
    )
    op.create_index(op.f("ix_competition_sport_id"), "competition", ["sport_id"], unique=False)
    op.create_table(
        "source_entity_map",
        sa.Column("source_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("canonical_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("reviewed_by", sa.Text(), nullable=True),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IN ('sport', 'competition', 'season', 'team', 'venue', 'event', 'bookmaker', 'market', 'selection')",
            name=op.f("ck_source_entity_map_entity_type"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_source_entity_map_confidence_range"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_source_entity_map_valid_range"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_source_entity_map_source_id_source")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_entity_map")),
    )
    op.create_index(
        op.f("ix_source_entity_map_canonical_id"),
        "source_entity_map",
        ["canonical_id"],
        unique=False,
    )
    op.create_index(
        "uq_source_entity_map_current",
        "source_entity_map",
        ["source_id", "entity_type", "external_id"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "team",
        sa.Column("sport_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("country_code", sa.String(length=8), nullable=True),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("home_venue_id", sa.CHAR(length=26, collation="C"), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('senior_men', 'senior_women', 'youth', 'reserve', 'other')",
            name=op.f("ck_team_category"),
        ),
        sa.ForeignKeyConstraint(
            ["home_venue_id"], ["venue.id"], name=op.f("fk_team_home_venue_id_venue")
        ),
        sa.ForeignKeyConstraint(["sport_id"], ["sport.id"], name=op.f("fk_team_sport_id_sport")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team")),
    )
    op.create_index(op.f("ix_team_sport_id"), "team", ["sport_id"], unique=False)
    op.create_table(
        "season",
        sa.Column("competition_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date", name=op.f("ck_season_date_range")
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competition.id"],
            name=op.f("fk_season_competition_id_competition"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_season")),
        sa.UniqueConstraint("competition_id", "label", name=op.f("uq_season_competition_id_label")),
    )
    op.create_table(
        "team_alias",
        sa.Column("team_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.Column("source_id", sa.CHAR(length=26, collation="C"), nullable=True),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_team_alias_valid_range")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_team_alias_source_id_source")
        ),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], name=op.f("fk_team_alias_team_id_team")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_alias")),
    )
    op.create_index(op.f("ix_team_alias_team_id"), "team_alias", ["team_id"], unique=False)
    op.create_index(
        "uq_team_alias_current",
        "team_alias",
        ["team_id", "alias", "lang", "source_id"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "event",
        sa.Column("season_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("home_team_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("away_team_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("venue_id", sa.CHAR(length=26, collation="C"), nullable=True),
        sa.Column("neutral_venue", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "neutral_venue_inferred", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("scheduled_kickoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("stage", sa.Text(), nullable=True),
        sa.Column("round", sa.Text(), nullable=True),
        sa.Column("duplicate_of_id", sa.CHAR(length=26, collation="C"), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'postponed', 'rescheduled', 'abandoned', 'suspended', 'cancelled', 'awarded', 'played')",
            name=op.f("ck_event_status"),
        ),
        sa.CheckConstraint("home_team_id <> away_team_id", name=op.f("ck_event_distinct_teams")),
        sa.ForeignKeyConstraint(
            ["away_team_id"], ["team.id"], name=op.f("fk_event_away_team_id_team")
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_id"], ["event.id"], name=op.f("fk_event_duplicate_of_id_event")
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"], ["team.id"], name=op.f("fk_event_home_team_id_team")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["season.id"], name=op.f("fk_event_season_id_season")
        ),
        sa.ForeignKeyConstraint(["venue_id"], ["venue.id"], name=op.f("fk_event_venue_id_venue")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event")),
    )
    op.create_index(op.f("ix_event_away_team_id"), "event", ["away_team_id"], unique=False)
    op.create_index(op.f("ix_event_home_team_id"), "event", ["home_team_id"], unique=False)
    op.create_index(
        "ix_event_season_id_scheduled_kickoff",
        "event",
        ["season_id", "scheduled_kickoff"],
        unique=False,
    )
    op.create_table(
        "event_status_history",
        sa.Column("event_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("previous_status", sa.String(length=16), nullable=True),
        sa.Column("source_id", sa.CHAR(length=26, collation="C"), nullable=True),
        sa.Column("source_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'postponed', 'rescheduled', 'abandoned', 'suspended', 'cancelled', 'awarded', 'played')",
            name=op.f("ck_event_status_history_status"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["event.id"], name=op.f("fk_event_status_history_event_id_event")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_event_status_history_source_id_source")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_status_history")),
    )
    op.create_index(
        op.f("ix_event_status_history_event_id"), "event_status_history", ["event_id"], unique=False
    )
    op.create_table(
        "kickoff_history",
        sa.Column("event_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("scheduled_kickoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("previous_kickoff", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_id", sa.CHAR(length=26, collation="C"), nullable=True),
        sa.Column("source_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["event.id"], name=op.f("fk_kickoff_history_event_id_event")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_kickoff_history_source_id_source")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kickoff_history")),
    )
    op.create_index(
        op.f("ix_kickoff_history_event_id"), "kickoff_history", ["event_id"], unique=False
    )
    op.create_table(
        "market",
        sa.Column("event_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("contract_signature", sa.String(length=256), nullable=False),
        sa.Column("market_family", sa.String(length=64), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("line", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("line_semantics", sa.String(length=16), nullable=True),
        sa.Column("settlement_basis", sa.String(length=32), nullable=False),
        sa.Column("void_policy_class", sa.String(length=128), nullable=False),
        sa.Column("contract", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_id"], ["event.id"], name=op.f("fk_market_event_id_event")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market")),
        sa.UniqueConstraint(
            "event_id", "contract_signature", name=op.f("uq_market_event_id_contract_signature")
        ),
    )
    op.create_table(
        "selection",
        sa.Column("market_id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("id", sa.CHAR(length=26, collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["market_id"], ["market.id"], name=op.f("fk_selection_market_id_market")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_selection")),
        sa.UniqueConstraint("market_id", "code", name=op.f("uq_selection_market_id_code")),
    )
    # ### end Alembic commands ###

    # --- hand-written: guards, partitions, seed ---------------------------------------
    for stmt in FUNCTIONS_SQL:
        op.execute(stmt)
    for table in ("audit_log", "event_status_history", "kickoff_history"):
        for stmt in append_only_triggers(table):
            op.execute(stmt)
    for table in ("team_alias", "source_entity_map"):
        for stmt in bitemporal_triggers(table):
            op.execute(stmt)
    # Previous month + 15 ahead. A scheduled job must keep calling
    # edgeledger_ensure_monthly_partitions (app.core.ddl.ensure_monthly_partitions).
    op.execute(
        "SELECT edgeledger_ensure_monthly_partitions('audit_log', "
        "(date_trunc('month', now() AT TIME ZONE 'UTC') - interval '1 month')::date, 16)"
    )
    op.execute(
        f"INSERT INTO sport (id, code, name) VALUES ('{FOOTBALL_SPORT_ID}', 'football', "  # noqa: S608
        "'Football (soccer)')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("selection")
    op.drop_table("market")
    op.drop_index(op.f("ix_kickoff_history_event_id"), table_name="kickoff_history")
    op.drop_table("kickoff_history")
    op.drop_index(op.f("ix_event_status_history_event_id"), table_name="event_status_history")
    op.drop_table("event_status_history")
    op.drop_index("ix_event_season_id_scheduled_kickoff", table_name="event")
    op.drop_index(op.f("ix_event_home_team_id"), table_name="event")
    op.drop_index(op.f("ix_event_away_team_id"), table_name="event")
    op.drop_table("event")
    op.drop_index(
        "uq_team_alias_current",
        table_name="team_alias",
        postgresql_where=sa.text("valid_to IS NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index(op.f("ix_team_alias_team_id"), table_name="team_alias")
    op.drop_table("team_alias")
    op.drop_table("season")
    op.drop_index(op.f("ix_team_sport_id"), table_name="team")
    op.drop_table("team")
    op.drop_index(
        "uq_source_entity_map_current",
        table_name="source_entity_map",
        postgresql_where=sa.text("valid_to IS NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index(op.f("ix_source_entity_map_canonical_id"), table_name="source_entity_map")
    op.drop_table("source_entity_map")
    op.drop_index(op.f("ix_competition_sport_id"), table_name="competition")
    op.drop_table("competition")
    op.drop_table("bookmaker_ruleset")
    op.drop_table("venue")
    op.drop_table("sport")
    op.drop_table("source")
    op.drop_table("bookmaker")
    op.drop_index("ix_audit_log_target", table_name="audit_log")
    op.drop_index("ix_audit_log_actor_id", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
    for stmt in DROP_FUNCTIONS_SQL:
        op.execute(stmt)
